services:
  manager:
    build: .
    image: cloakhq/cloakbrowser-manager:latest
    ports:
      - "127.0.0.1:9080:9080"
    volumes:
      - /mnt/administration-share/cloakbrowser-manager/data:/data
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN:-}
